### ISSUE TITLE
Error: 'assertion failed'

### ISSUE THREAD

**Issue by tanapaydin** [tradle/react-native-ecc#1]
This code currently doesn't work on ios. When I use the how-to-use code exactly given on the README file, I get the following error. It looks like there is a problem with the way the SIGN function is called.

if (!statement) throw new Error(errMsg || 'assertion failed')

**Comment by mvayngrib** [comment]
@tanapaydin you're right! I didn't update the docs after updating the method signature. Check out `index.js` to see the new method signature. Care to make a PR to update the readme?

**Comment by tanapaydin** [comment]
@mvayngrib, as a team we need to decide whether this library serves our needs or not asap. What we need is a typical ecc scenario. We need private and public keys produced. We'll keep the private key secret, and hand over the public key to our client. Then, using the private key we need to sign the data. After that, on the client side we need to verify the signed data using the public key.

It looks like, your code only produces 1 key and I think it's called pub (does it refer to public?). Do you think we can bend your code to fulfil our needs.

**Comment by mvayngrib** [comment]
@tanapaydin as many keys as you want. I made you a simple example: https://github.com/mvayngrib/ecctest

**Comment by tanapaydin** [comment]
@mvayngrib, thanks a lot for the example. You provided 2 keys and used the first key to sign the data. Can you verify that signed-data with the second key you have? That's actually the point we're seeking for.

Here's an example what we're actually trying to achieve.

var crypto = require("crypto");
var eccrypto = require("eccrypto");

// A new random 32-byte private key.
var privateKey = crypto.randomBytes(32);
// Corresponding uncompressed (65-byte) public key.
var publicKey = eccrypto.getPublic(privateKey);

var str = "message to sign";
// Always hash you message to sign!
var msg = crypto.createHash("sha256").update(str).digest();

eccrypto.sign(privateKey, msg).then(function(sig) {
  console.log("Signature in DER format:", sig);
  eccrypto.verify(publicKey, msg, sig).then(function() {
    console.log("Signature is OK");
  }).catch(function() {
    console.log("Signature is BAD");
  });
});

**Comment by mvayngrib** [comment]
@tanapaydin yes, what a private key signs, the corresponding public key can verify. I updated the readme, so take a look at the example there.

**Comment by tanapaydin** [comment]
@mvayngrib, react-native-ecc doesn't produce a proper keyPair. It only produces the public key, and also the sign and verify functions. It doesn't have a private key. So we cannot use it in our project. I'll close the issue since you've updated the documentation. Thanks a bunch.

**Comment by mvayngrib** [comment]
@tanapaydin right, if you want to actually be able to export the private key, use something like [elliptic](https://github.com/indutny/elliptic). The advantage of using react-native-ecc is that private keys live in the native keychain, and thus are much harder to steal. All you can do is perform operations with them, like sign/verify and only the public key is exportable.
