### ISSUE TITLE
Error: serviceID can only be set once.

### ISSUE THREAD

**Issue by smaldd14** [tradle/react-native-ecc#11]
Every time I make a change to my code and reload, I get an error saying serviceID can only be set once. I set the serviceID outside on the constructor, but I still get an error when the page reloads. Where should I set the serviceID?

**Comment by mvayngrib** [comment]
@smaldd14 i'm unfamiliar with your code, but u need to avoid calling this function more than once: https://github.com/tradle/react-native-ecc/blob/master/index.js#L41

**Comment by smaldd14** [comment]
> 
> 
> @smaldd14 i'm unfamiliar with your code, but u need to avoid calling this function more than once: https://github.com/tradle/react-native-ecc/blob/master/index.js#L41

**Comment by smaldd14** [comment]
@mvayngrib Where would you suggest calling this?

**Comment by mvayngrib** [comment]
@smaldd14 that's up to you :) for example, in your entrypoint `src/index.js`

```js
// index.js
import ecc from 'react-native-ecc'
import App from './App'

ecc.setServiceID('my-app-name')

...
AppRegistry.registerComponent(appName, () => App)
```
