### ISSUE TITLE
create keypair ends with OSStatus -25291

### ISSUE THREAD

**Issue by ivanpagac** [tradle/react-native-ecc#4]
Hello, creating keypair on real device ends with code OSStatus -25291. On simulator however it works with no problem. 
[https://www.osstatus.com/search/results?platform=all&framework=all&search=25291](url)

**Comment by ivanpagac** [comment]
ok, so the issue is away if i set up passcode or touch id, without it it is not working

**Comment by mvayngrib** [comment]
@ivanpagac yep, without the passcode, it doesn't work, i should update the readme

for reference, this line is the culprit: https://github.com/tradle/react-native-ecc/blob/master/ios/RNECC.m#L74

this could be made a passed-in option
