### ISSUE TITLE
broken package

### ISSUE THREAD

**Issue by downTheFallLine** [tradle/react-native-ecc#5]
fails upon import with  

null is not an object (evaluating 'RNECC.preHash')

**Comment by mvayngrib** [comment]
it means u haven't linked the library correctly, see:
https://github.com/tradle/react-native-ecc#installation

**Comment by downTheFallLine** [comment]
Thanks for the feedback.   I tried that… see below…. With same result


toms-MBP-2:zzz tomdanner$ npm install react-native-ecc --save

npm WARN react-google-maps@9.4.5 requires a peer of @types/googlemaps@^3.0.0 but none is installed. You must install peer dependencies yourself.

npm WARN react-google-maps@9.4.5 requires a peer of @types/markerclustererplus@^2.1.29 but none is installed. You must install peer dependencies yourself.

npm WARN react-google-maps@9.4.5 requires a peer of @types/react@^15.0.0 || ^16.0.0 but none is installed. You must install peer dependencies yourself.

npm WARN react-native-reanimated@1.0.1 requires a peer of react@16.0.0-alpha.6 but none is installed. You must install peer dependencies yourself.

npm WARN react-native-reanimated@1.0.1 requires a peer of react-native@^0.44.1 but none is installed. You must install peer dependencies yourself.



+ react-native-ecc@2.2.0

added 5 packages from 5 contributors and audited 37851 packages in 10.451s

found 11 low severity vulnerabilities

  run `npm audit fix` to fix them, or `npm audit` for details

toms-MBP-2:zzz tomdanner$ react-native link

**Comment by downTheFallLine** [comment]
btw, my target device is IOS.  i dont care about droid.  is there some other SECRET UNDOCUMENTED DEPENDENCY thats required for all of this to work in the IOS world.  i started with  a raw expo project, nothing fancy.

**Comment by mvayngrib** [comment]
expo doesn't work with custom native modules, you'll have to eject
