### ISSUE TITLE
Get the private key

### ISSUE THREAD

**Issue by guipublic** [tradle/react-native-ecc#9]
The API does not expose the private key, I was wondering if it would be possible to retrieve it?

**Comment by mvayngrib** [comment]
@guipublic no, as the goal was to store the private keys in the SecureEnclave if possible (so that they can't be extracted) https://github.com/tradle/react-native-ecc/blob/master/ios/RNECC.m#L130

**Comment by guipublic** [comment]
Thank you for the precision, it makes sense indeed.
